### ISSUE TITLE
Invidious Companion Support?

### ISSUE THREAD

**Issue by iammer** [iBicha/playlet#572]
I switched to using [Invidious companion](https://github.com/iv-org/invidious-companion) today.  While I can play videos without issue though the invidious web interface, when I try to use Playlet I get an `errorMsg: no valid bitrates` message trying to play any video.  I can see in my companion logs calls to `/videoplayback` are getting a `400` response when requested by Playlet, but a `206` response when requested from the browser.    I have tried clearing the Playlet cache, closing the app, restarting, logging out and back in, etc.  but none of those things resolved the issue.

Comparing the 2 requests from the companion logs, I see that my browser is including the following 3 parameters that Playlet is not: 
`alr=no`
`cpn=`
`host=rr5---sn-q0cedn7s.googlevideo.com`

Is this expected?  Does Playlet support Invidious companion?

**Comment by iBicha** [comment]
I tried to chase this down, as I haven't setup companion myself.
It looks to me that the companion is not supporting API yet.
https://github.com/iv-org/invidious-companion/issues/22
> [Renaming this to supporting Invidious API, something that it is not a priority as of now.]( https://github.com/iv-org/invidious-companion/issues/22#issuecomment-2549760237)

Now I'm not sure if this will help or not, but can you try change the "Proxy videos" to "Always" in Playlet settings?

**Comment by iammer** [comment]
> Now I'm not sure if this will help or not, but can you try change the "Proxy videos" to "Always" in Playlet settings?

Unfortunately, I already have it set to "Always".

**Comment by iBicha** [comment]
Thanks for trying, was worth a try.
So this is really dependant on API support, Invidious API need to return deciphered urls that Playlet can consume.

**Comment by iammer** [comment]
Hey @iBicha, I dug into this a bit.   I don't think the issue is actually https://github.com/iv-org/invidious-companion/issues/22, I took a stab at fixing that before I realized it wasn't actually the issue.

The way I have invidious companion set up (and I think this is common).  The Nginx that sits in front of both invidious and invidious companion forwards /latest_version, /api/manifest/dash/id/, and /videoplayback to companion.   Everything else (including /api/v1/videos/) goes to invidious.  So implementing the /api/v1/videos/ endpoint in invidious companion wouldn't have changed anything.

 I think the real problem may be https://github.com/iBicha/playlet/blob/main/playlet-lib/src/components/Services/Invidious/InvidiousService.bs#L147.   There should be a local=true parameter set in that URL if `preferences["invidious.proxy_videos"]` is "always".   Invidious api returns different slightly different urls when local=true is set.   See: https://github.com/iv-org/invidious/blob/master/src/invidious/jsonify/api_v1/video_json.cr#L95

I was able to confirm this by creating a new build of invidious that defaults that local parameter to true when not set.   Using that, Playlet with invidious companion works fine.

Also to clarify something above, Playlet actually works fine with invidious companion when "Proxy Videos" is **not** set to "Always" (as I mentioned above I already had that set to "Always"; my invidious server connects through a VPN and I want all youtube traffic to go through that).  I had not tried setting to "Never" until today.

**Comment by iBicha** [comment]
Thanks a lot for digging into this! Good stuff
Although I see the point that Playlet should set the local arg, but I don't think this is necessarily the issue.
That's because Playlet asks Invidious for video stream urls (most importantly, decrypted) and then does the rest.
That includes generating the [DashManifest](https://github.com/iBicha/playlet/blob/main/playlet-lib/src/components/Services/Dash/DashManifest.bs), including [handling the urls](https://github.com/iBicha/playlet/blob/fc7a029147e3424a90fd48cff07122907054fd97/playlet-lib/src/components/Services/Dash/DashManifest.bs#L40-L44)

So I spun up a local instance and tried it on Playlet, looks like this
```
version: "3"
services:

  invidious:
    image: quay.io/invidious/invidious:master
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: invidious-db
          port: 5432
        check_tables: true
        invidious_companion:
        - private_url: "http://companion:8282"
          public_url: "http://localhost:8282"
        invidious_companion_key: "1234567890123456"
        external_port: 3000
        domain: 192.168.18.16
        # https_only: false
        # statistics_enabled: false
        # Use the key generated in the 2nd step
        hmac_key: "1234567890123456"
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/trending || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db

  companion:
    image: quay.io/invidious/invidious-companion:latest
    environment:
       - SERVER_SECRET_KEY=1234567890123456 
    restart: unless-stopped
    ports:
      - "8282:8282"
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    cap_drop:
      - ALL
    read_only: true
    volumes:
      - companioncache:/var/tmp/youtubei.js:rw
    security_opt:
      - no-new-privileges:true

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

volumes:
  postgresdata:
  companioncache:
```

And surprisingly, it looks like it works, fine. Here's my Playlet settings for clarity
```
{
    "__version": 3,
    "dev.dev_video_player": false,
    "invidious.instance": "http://192.168.18.16:3000",
    "invidious.proxy_videos": "if_needed",
    "misc.home_screen_layout": [
        {
            "enabled": true,
            "id": "recommended"
        },
        {
            "enabled": true,
            "id": "subscriptions"
        },
        {
            "enabled": true,
            "id": "playlists"
        },
        {
            "enabled": true,
            "id": "watch_history"
        },
        {
            "enabled": true,
            "id": "trending"
        },
        {
            "enabled": true,
            "id": "trending_music"
        },
        {
            "enabled": true,
            "id": "trending_movies"
        },
        {
            "enabled": true,
            "id": "trending_gaming"
        },
        {
            "enabled": true,
            "id": "popular"
        }
    ],
    "misc.queue_notifications": true,
    "playback.autoplay": true,
    "playback.backend": "invidious",
    "playback.preferred_quality": "auto",
    "search_history.enabled": true,
    "sponsorblock.enabled": true,
    "sponsorblock.show_notifications": true
}
```

Now I'm wondering if the issue is specific to your Invidious setup? If your Invidious instance is exposed to the internet, I can help investigate this with you (you can share your instance with me via email if you do not wish to post it here, please find my email in the info page of the Playlet web app)
