### ISSUE TITLE
Intermittent 'error playing video' issues

### ISSUE THREAD

**Issue by mattmcquinn** [iBicha/playlet#74]
Hi,
I have been having issues with playlet not being able to play some videos while playing others just fine.
The error message I get is the same as the error reported in issue #42

```
Error playing video
...
dbgmsg: got invalid pathname, load the next one
category: mediaplayer
errcode: 8
drmerrcode: 0
```

This is using my local instance and all videos work fine using Invidious in my browser.
I fixed my docker configuration and that fixed my image loading problem, but I still consistently get errors when playing some videos.

Here are some videos that are throwing the above error.
```
9mSmLI9imQk - youtube short
t5Qv86FZ2Xo - normal video
3aBPKONrAeU - normal video
2voCtSF5XTs - normal video
3inw26U-os4 - normal video
```

Here is the current api_state

```
{
    "app": {
        "git_commit_hash": "322232a02788e8c16bc8fdcff10b74e1685917ed",
        "id": "dev",
        "lib_git_commit_hash": "322232a02788e8c16bc8fdcff10b74e1685917ed",
        "lib_version": "0.9.0",
        "version": "0.9.0"
    },
    "device": {
        "display_aspect_ratio": "16x9",
        "display_mode": "720p",
        "display_size": {
            "h": 720,
            "w": 1280
        },
        "display_type": "HDTV",
        "graphics_platform": "opengl",
        "internet_status": true,
        "model_type": "TV",
        "os_version": {
            "build": "4323",
            "major": "11",
            "minor": "5",
            "revision": "0"
        },
        "ui_resolution": {
            "height": 1080,
            "name": "FHD",
            "width": 1920
        },
        "video_mode": "2160p60"
    },
    "invidious": {
        "auth_url": "http://myserver.local:3000/authorize_token?scopes=GET%3Afeed%2CGET%3Aplaylists%2CPOST%3Atokens%2Funregister%2CPOST%3Ahistory*&callback_url=http%3A%2F%2F192.168.69.172%3A8888%2Finvidious%2Ftoken_callback%3Fref%3Dhttp%3A%2F%2Fmyserver.local%3A3000&expire=1745340605",
        "instances": [
            "http://myserver.local:3000"
        ],
        "logged_in": true,
        "logged_in_instance": "http://myserver.local:3000",
        "logged_in_username": "username",
        "selected_instance": "http://myserver.local:3000"
    }
}
```

Thanks in advance for your help. Playlet has been really great to use!

**Comment by iBicha** [comment]
Thanks for reporting this issue. All these videos work for me on my local instance, so hard to diagnose. 

To narrow things down
- Since only some of the videos work fine, and only these are affected, we're going to assume it's not a config issue probably
- Since the videos in question work in the browser, I would assume these are not geo-blocked

Perhaps this is hardware specific? (Specific hardware doesn't like specific video encoding?) that would be just a theory, but also unlikely

That error message is not well documented from what I can see. We will need to investigate further.

**Comment by mattmcquinn** [comment]
Thanks for the quick reply and verifying the videos work on your machine.

If I wanted to dig into what might be the root cause, are you able to point me in the right direction?
I'm guessing I need to dig into Playlet logs to find more information or maybe a stacktrace.

I work as a developer and would like to contribute back to the project if possible.

Let me know if you think there is anything I can do to gather more information.

**Comment by iBicha** [comment]
I appreciate your interest in contributing!
I can give you a couple of pointers on debugging playlet
- Start with [Enabling Roku Developer Mode](https://github.com/iBicha/playlet#enable-roku-developer-mode)
- [Setup for development](https://github.com/iBicha/playlet#development)
- In vs code, make sure [BrightScript Language](https://marketplace.visualstudio.com/items?itemName=RokuCommunity.brightscript) extension is installed 
- Press the play button, with the `Playlet (dev)` target selected. This will build Playlet it and run it on your TV with the debugger connected to vs code. You should also see Playlet logging all web requests it is making in vs code 
<img width="1023" alt="Screen Shot 2023-04-26 at 8 27 39 AM" src="https://user-images.githubusercontent.com/17722782/234574468-2fc126fc-171b-457f-a5fa-e6a8a110a660.png">



Now for some details on how playing a video works
- When a video is launched, we make a [list possible video streams of that video](https://github.com/iBicha/playlet/blob/f1d091941fbdb3a3a0ce570501d30158f0a8fb63/playlet-lib/src/components/VideoPlayer/VideoPlayer.bs#L107)
- The list is typically:
  - A DASH video
  - A DASH video with local set to `true`
  - A stream format
  - A stream format with local set to `true`

To explain what these mean:
- DASH stands for [Dynamic Adaptive Streaming over HTTP](https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP). It is simply an xml manifest that contains the links to the video in many resolutions. Then based on your internet speed, the best quality among then will be selected.
- A format stream is simply a direct link to a video. Usually a 720p video most of the time.
- local set to `true`, means that the video will not be streamed directly from Youtube servers, but instead will be proxied through Invidious. The video data will be downloaded by your instance, and Playlet will consume it.

The reason to use these variations is to have options to try from when streaming fails. (DASH sometimes fail, or streaming without proxy sometimes fail because it was geo-blocked, or because Youtube detected the discrepancy in IP addresses between the your instance and your TV).

When an error like the one you're seeing shows up, it usually means none of the streams worked. This is that part of the code where [we detect an error and try the next stream available](https://github.com/iBicha/playlet/blob/f1d091941fbdb3a3a0ce570501d30158f0a8fb63/playlet-lib/src/components/VideoPlayer/VideoPlayer.bs#L264)

Try to inspect the logs, see if something interesting comes up. I'll be happy to assist you if there's more info about this issue!

I hope this helps

**Comment by iBicha** [comment]
I realize now there's no easy way to gather logs fully without going into development mode. I've added an item to the roadmap to make collecting logs easier, [kinda similar to how Plex does it](https://support.plex.tv/articles/201377603-roku-logs/)

**Comment by mattmcquinn** [comment]
Thanks for the detailed replies. I'll try to get setup this weekend.

**Comment by KyTiXo** [comment]
@mattmcquinn what did you change in your docker config to fix your image issue? I'm having a similar issue with thumbnails not loading on Roku but work in browser 

I'm running it behind a Traefik proxy, so I'm sure something isn't configured right 😅

**Comment by mattmcquinn** [comment]
> @mattmcquinn what did you change in your docker config to fix your image issue? I'm having a similar issue with thumbnails not loading on Roku but work in browser
> 
> I'm running it behind a Traefik proxy, so I'm sure something isn't configured right 😅

It has been a while since I have run invidious so I'm not exactly which change fixed it but I'll paste my docker-compose file here. If I had to guess it may have been my change under the `ports` section.

```
version: "3"
services:

  invidious:
    image: quay.io/invidious/invidious:latest
    # image: quay.io/invidious/invidious:latest-arm64 # ARM64/AArch64 devices
    restart: never
    ports:
      - "3000:3000"
    environment:
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: invidious-db
          port: 5432
        check_tables: true
        hmac_key: redacted
        external_port: 3000
        domain: redacted.local
        https_only: false
        # statistics_enabled: false
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db

  invidious-db:
    image: docker.io/library/postgres:14
    restart: never
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

volumes:
  postgresdata:
```
